version: "3.8"

services:
  web:
    build:
      context: .
    command: sh /app/entrypoint.sh
    expose:
      - "8000"
    env_file:
      .env
    volumes:
      - .:/app
      - back_static:/app/static 
      - back_media:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  celery_worker:
    build:
      context: .
    command: celery -A shop_api worker --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      .env
    volumes:
      - .:/app

  celery_beat:
    build:
      context: .
    command: celery -A shop_api beat --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      .env
    volumes:
      - .:/app

  celery_flower:
    build:
      context: .
    command: celery -A shop_api flower --port=5555
    ports:
      - "5556:5555"
    depends_on:
      redis:
        condition: service_healthy
      celery_worker:
        condition: service_started 
    env_file:
      .env
    volumes:
      - .:/app

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - back_static:/app/static
      - back_media:/app/media



volumes:
  db-data:
  redis-data:
  back_static:
  back_media:
  

  
    
    

  


